export const data = [
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "rbourner0@archive.org",
      fname: "Rickie",
      lname: "Bourner",
      role: "student",
      initialPassword: "9v9fifga",
    },
    ranks: {
      u1: 8,
      u2: 4,
      u3: 2,
      u4: 2,
      u5: 4,
      u6: 7,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 64,
      contact_add: 6391154067,
      email: "ningley1@baidu.com",
      fname: "Neysa",
      lname: "Ingley",
      role: "student",
      initialPassword: "ud56jo2n",
    },
    ranks: {
      u1: 7,
      u2: 10,
      u3: 8,
      u4: 10,
      u5: 7,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 45,
      contact_add: 6391154067,
      email: "wcasey2@php.net",
      fname: "Willette",
      lname: "Casey",
      role: "student",
      initialPassword: "qwu8ts9x",
    },
    ranks: {
      u1: 6,
      u2: 5,
      u3: 3,
      u4: 3,
      u5: 9,
      u6: 10,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 54,
      contact_add: 6391154067,
      email: "iseacroft3@si.edu",
      fname: "Ike",
      lname: "Seacroft",
      role: "student",
      initialPassword: "zb3arg8g",
    },
    ranks: {
      u1: 4,
      u2: 8,
      u3: 9,
      u4: 6,
      u5: 2,
      u6: 9,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 34,
      contact_add: 6391154067,
      email: "dmilverton4@sohu.com",
      fname: "Deeanne",
      lname: "Milverton",
      role: "student",
      initialPassword: "d6zfot7b",
    },
    ranks: {
      u1: 9,
      u2: 3,
      u3: 4,
      u4: 7,
      u5: 3,
      u6: 5,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 43,
      contact_add: 6391154067,
      email: "dclibbery5@mit.edu",
      fname: "Debee",
      lname: "Clibbery",
      role: "student",
      initialPassword: "6xexyba1",
    },
    ranks: {
      u1: 2,
      u2: 8,
      u3: 7,
      u4: 7,
      u5: 4,
      u6: 2,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 65,
      contact_add: 6391154067,
      email: "rmclenahan6@ca.gov",
      fname: "Ruperto",
      lname: "McLenahan",
      role: "student",
      initialPassword: "h7r6eb2r",
    },
    ranks: {
      u1: 8,
      u2: 3,
      u3: 8,
      u4: 2,
      u5: 5,
      u6: 9,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 65,
      contact_add: 6391154067,
      email: "bwewell7@google.de",
      fname: "Beilul",
      lname: "Wewell",
      role: "student",
      initialPassword: "zn2q1n0v",
    },
    ranks: {
      u1: 7,
      u2: 4,
      u3: 8,
      u4: 3,
      u5: 10,
      u6: 5,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 45,
      contact_add: 6391154067,
      email: "ggrabban8@github.com",
      fname: "Germana",
      lname: "Grabban",
      role: "student",
      initialPassword: "gascjlkg",
    },
    ranks: {
      u1: 4,
      u2: 3,
      u3: 4,
      u4: 5,
      u5: 3,
      u6: 3,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 76,
      contact_add: 6391154067,
      email: "mfranciottoi9@aol.com",
      fname: "Maudie",
      lname: "Franciottoi",
      role: "student",
      initialPassword: "0wihr1n8",
    },
    ranks: {
      u1: 7,
      u2: 5,
      u3: 7,
      u4: 4,
      u5: 3,
      u6: 9,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "rbonnora@weather.com",
      fname: "Roshelle",
      lname: "Bonnor",
      role: "student",
      initialPassword: "yxv7im3q",
    },
    ranks: {
      u1: 4,
      u2: 3,
      u3: 8,
      u4: 5,
      u5: 4,
      u6: 7,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 45,
      contact_add: 6391154067,
      email: "gchmielb@fema.gov",
      fname: "Grange",
      lname: "Chmiel",
      role: "student",
      initialPassword: "zpecbpob",
    },
    ranks: {
      u1: 8,
      u2: 10,
      u3: 8,
      u4: 10,
      u5: 4,
      u6: 10,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 43,
      contact_add: 6391154067,
      email: "lolanderc@hud.gov",
      fname: "Lynna",
      lname: "Olander",
      role: "student",
      initialPassword: "xd0xhn9t",
    },
    ranks: {
      u1: 4,
      u2: 10,
      u3: 2,
      u4: 7,
      u5: 10,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 34,
      contact_add: 6391154067,
      email: "rthrushd@businessweek.com",
      fname: "Ruthann",
      lname: "Thrush",
      role: "student",
      initialPassword: "d7tn4mmy",
    },
    ranks: {
      u1: 4,
      u2: 7,
      u3: 10,
      u4: 7,
      u5: 4,
      u6: 2,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 75,
      contact_add: 6391154067,
      email: "agirardete@stumbleupon.com",
      fname: "Abrahan",
      lname: "Girardet",
      role: "student",
      initialPassword: "tty9mq8m",
    },
    ranks: {
      u1: 5,
      u2: 3,
      u3: 4,
      u4: 8,
      u5: 3,
      u6: 9,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 75,
      contact_add: 6391154067,
      email: "gmacilriachf@redcross.org",
      fname: "Gladys",
      lname: "MacIlriach",
      role: "student",
      initialPassword: "sdb0n7n9",
    },
    ranks: {
      u1: 9,
      u2: 8,
      u3: 10,
      u4: 7,
      u5: 9,
      u6: 3,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 64,
      contact_add: 6391154067,
      email: "rmcgowang@cnet.com",
      fname: "Ramsay",
      lname: "McGowan",
      role: "student",
      initialPassword: "anzzw04h",
    },
    ranks: {
      u1: 5,
      u2: 4,
      u3: 9,
      u4: 6,
      u5: 10,
      u6: 2,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 45,
      contact_add: 6391154067,
      email: "laisthorpeh@rambler.ru",
      fname: "Lila",
      lname: "Aisthorpe",
      role: "student",
      initialPassword: "eucyqlld",
    },
    ranks: {
      u1: 8,
      u2: 10,
      u3: 7,
      u4: 2,
      u5: 10,
      u6: 4,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 45,
      contact_add: 6391154067,
      email: "rlittledykei@discuz.net",
      fname: "Ripley",
      lname: "Littledyke",
      role: "student",
      initialPassword: "7qbduwdj",
    },
    ranks: {
      u1: 2,
      u2: 7,
      u3: 10,
      u4: 9,
      u5: 3,
      u6: 3,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 34,
      contact_add: 6391154067,
      email: "eheaneyj@alexa.com",
      fname: "Englebert",
      lname: "Heaney",
      role: "student",
      initialPassword: "psqwqbfs",
    },
    ranks: {
      u1: 2,
      u2: 9,
      u3: 10,
      u4: 9,
      u5: 7,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 75,
      contact_add: 6391154067,
      email: "einkink@home.pl",
      fname: "Elysee",
      lname: "Inkin",
      role: "student",
      initialPassword: "ji8keqwp",
    },
    ranks: {
      u1: 7,
      u2: 9,
      u3: 4,
      u4: 6,
      u5: 7,
      u6: 10,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 75,
      contact_add: 6391154067,
      email: "dedmensonl@mac.com",
      fname: "Danielle",
      lname: "Edmenson",
      role: "student",
      initialPassword: "tbw9tf4r",
    },
    ranks: {
      u1: 4,
      u2: 7,
      u3: 3,
      u4: 10,
      u5: 9,
      u6: 10,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 43,
      contact_add: 6391154067,
      email: "kkinlochm@engadget.com",
      fname: "Karie",
      lname: "Kinloch",
      role: "student",
      initialPassword: "64rp52zy",
    },
    ranks: {
      u1: 7,
      u2: 3,
      u3: 9,
      u4: 3,
      u5: 7,
      u6: 7,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 75,
      contact_add: 6391154067,
      email: "nclayilln@auda.org.au",
      fname: "Nadine",
      lname: "Clayill",
      role: "student",
      initialPassword: "38pnygoe",
    },
    ranks: {
      u1: 7,
      u2: 2,
      u3: 4,
      u4: 8,
      u5: 6,
      u6: 5,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 65,
      contact_add: 6391154067,
      email: "mmuscotto@ibm.com",
      fname: "Maurise",
      lname: "Muscott",
      role: "student",
      initialPassword: "qcmdjrx7",
    },
    ranks: {
      u1: 5,
      u2: 6,
      u3: 4,
      u4: 4,
      u5: 5,
      u6: 4,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "wchrismasp@vimeo.com",
      fname: "Westleigh",
      lname: "Chrismas",
      role: "student",
      initialPassword: "khr0q4g4",
    },
    ranks: {
      u1: 8,
      u2: 7,
      u3: 2,
      u4: 5,
      u5: 5,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "jmalacridaq@tinypic.com",
      fname: "Joanna",
      lname: "Malacrida",
      role: "student",
      initialPassword: "wxp11ozk",
    },
    ranks: {
      u1: 8,
      u2: 10,
      u3: 4,
      u4: 7,
      u5: 2,
      u6: 5,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "elunneyr@sfgate.com",
      fname: "Eustacia",
      lname: "Lunney",
      role: "student",
      initialPassword: "9tshcsrs",
    },
    ranks: {
      u1: 10,
      u2: 9,
      u3: 5,
      u4: 9,
      u5: 4,
      u6: 10,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 64,
      contact_add: 6391154067,
      email: "kbartels@myspace.com",
      fname: "Kim",
      lname: "Bartel",
      role: "student",
      initialPassword: "3fa0vwyk",
    },
    ranks: {
      u1: 7,
      u2: 2,
      u3: 8,
      u4: 2,
      u5: 8,
      u6: 5,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "apasset@gnu.org",
      fname: "Ayn",
      lname: "Passe",
      role: "student",
      initialPassword: "teh3qyop",
    },
    ranks: {
      u1: 10,
      u2: 6,
      u3: 6,
      u4: 4,
      u5: 10,
      u6: 4,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 75,
      contact_add: 6391154067,
      email: "ahabbenu@arstechnica.com",
      fname: "Alonso",
      lname: "Habben",
      role: "student",
      initialPassword: "acjmuqu9",
    },
    ranks: {
      u1: 7,
      u2: 5,
      u3: 5,
      u4: 2,
      u5: 3,
      u6: 4,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 34,
      contact_add: 6391154067,
      email: "qlugardv@gov.uk",
      fname: "Quintina",
      lname: "Lugard",
      role: "student",
      initialPassword: "wq8hheme",
    },
    ranks: {
      u1: 10,
      u2: 4,
      u3: 2,
      u4: 3,
      u5: 6,
      u6: 2,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 54,
      contact_add: 6391154067,
      email: "jheaysmanw@4shared.com",
      fname: "Jilly",
      lname: "Heaysman",
      role: "student",
      initialPassword: "ytsmdiol",
    },
    ranks: {
      u1: 9,
      u2: 3,
      u3: 10,
      u4: 7,
      u5: 5,
      u6: 4,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "sbarhamsx@walmart.com",
      fname: "Sibella",
      lname: "Barhams",
      role: "student",
      initialPassword: "13rd8efg",
    },
    ranks: {
      u1: 3,
      u2: 5,
      u3: 7,
      u4: 5,
      u5: 7,
      u6: 6,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "hcarayoly@prweb.com",
      fname: "Humfrid",
      lname: "Carayol",
      role: "student",
      initialPassword: "d1bqdix9",
    },
    ranks: {
      u1: 7,
      u2: 2,
      u3: 9,
      u4: 8,
      u5: 5,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 76,
      contact_add: 6391154067,
      email: "emcgroutherz@phoca.cz",
      fname: "Elita",
      lname: "McGrouther",
      role: "student",
      initialPassword: "of0n5r5c",
    },
    ranks: {
      u1: 3,
      u2: 7,
      u3: 4,
      u4: 5,
      u5: 6,
      u6: 9,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 45,
      contact_add: 6391154067,
      email: "mhalliburton10@merriam-webster.com",
      fname: "Mord",
      lname: "Halliburton",
      role: "student",
      initialPassword: "pe4ifya8",
    },
    ranks: {
      u1: 2,
      u2: 5,
      u3: 8,
      u4: 2,
      u5: 10,
      u6: 3,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 33,
      contact_add: 6391154067,
      email: "jhastwall11@google.ru",
      fname: "Joice",
      lname: "Hastwall",
      role: "student",
      initialPassword: "3q80vydp",
    },
    ranks: {
      u1: 2,
      u2: 10,
      u3: 6,
      u4: 2,
      u5: 3,
      u6: 10,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 76,
      contact_add: 6391154067,
      email: "semanuele12@homestead.com",
      fname: "Salem",
      lname: "Emanuele",
      role: "student",
      initialPassword: "vau4hbkb",
    },
    ranks: {
      u1: 5,
      u2: 7,
      u3: 9,
      u4: 3,
      u5: 5,
      u6: 3,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 43,
      contact_add: 6391154067,
      email: "olenoir13@squarespace.com",
      fname: "Olly",
      lname: "Lenoir",
      role: "student",
      initialPassword: "75rjnxi2",
    },
    ranks: {
      u1: 9,
      u2: 3,
      u3: 6,
      u4: 9,
      u5: 6,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 33,
      contact_add: 6391154067,
      email: "vambroise14@irs.gov",
      fname: "Vinita",
      lname: "Ambroise",
      role: "student",
      initialPassword: "7x5omv39",
    },
    ranks: {
      u1: 10,
      u2: 4,
      u3: 2,
      u4: 7,
      u5: 2,
      u6: 9,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "ajore15@barnesandnoble.com",
      fname: "Aksel",
      lname: "Jore",
      role: "student",
      initialPassword: "1b0icgnt",
    },
    ranks: {
      u1: 8,
      u2: 5,
      u3: 3,
      u4: 8,
      u5: 5,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 43,
      contact_add: 6391154067,
      email: "ceasthope16@dot.gov",
      fname: "Cosmo",
      lname: "Easthope",
      role: "student",
      initialPassword: "wtgp1y35",
    },
    ranks: {
      u1: 10,
      u2: 6,
      u3: 8,
      u4: 3,
      u5: 3,
      u6: 2,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 45,
      contact_add: 6391154067,
      email: "kwindas17@google.co.jp",
      fname: "Killie",
      lname: "Windas",
      role: "student",
      initialPassword: "zqvepw4s",
    },
    ranks: {
      u1: 4,
      u2: 2,
      u3: 7,
      u4: 6,
      u5: 4,
      u6: 2,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "grubens18@tuttocitta.it",
      fname: "Gun",
      lname: "Rubens",
      role: "student",
      initialPassword: "nvljahb8",
    },
    ranks: {
      u1: 6,
      u2: 9,
      u3: 6,
      u4: 10,
      u5: 8,
      u6: 5,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 34,
      contact_add: 6391154067,
      email: "yvolke19@gov.uk",
      fname: "Yuri",
      lname: "Volke",
      role: "student",
      initialPassword: "95t2k1eh",
    },
    ranks: {
      u1: 3,
      u2: 6,
      u3: 4,
      u4: 8,
      u5: 10,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 23,
      contact_add: 6391154067,
      email: "zdolman1a@desdev.cn",
      fname: "Zoe",
      lname: "Dolman",
      role: "student",
      initialPassword: "vv1lsbeq",
    },
    ranks: {
      u1: 4,
      u2: 9,
      u3: 3,
      u4: 10,
      u5: 7,
      u6: 6,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 43,
      contact_add: 6391154067,
      email: "ffacchini1b@creativecommons.org",
      fname: "Filippo",
      lname: "Facchini",
      role: "student",
      initialPassword: "l4fnqnok",
    },
    ranks: {
      u1: 2,
      u2: 2,
      u3: 10,
      u4: 3,
      u5: 3,
      u6: 8,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 34,
      contact_add: 6391154067,
      email: "ccockin1c@ucoz.com",
      fname: "Corinne",
      lname: "Cockin",
      role: "student",
      initialPassword: "zv838dxe",
    },
    ranks: {
      u1: 3,
      u2: 8,
      u3: 10,
      u4: 7,
      u5: 5,
      u6: 6,
    },
  },
  {
    courseInfo: "AGO-DIC-2021_electromechanical_physical_1_A",
    account: {
      age: 45,
      contact_add: 6391154067,
      email: "felphinstone1d@weather.com",
      fname: "Forester",
      lname: "Elphinstone",
      role: "student",
      initialPassword: "32oagb97",
    },
    ranks: {
      u1: 6,
      u2: 7,
      u3: 5,
      u4: 3,
      u5: 7,
      u6: 3,
    },
  },
];
