export const students = [
  {
    id: 1,
    first_name: "asdf",
    last_name: "Sultan",
    gender: "M",
    age: 35,
    contact_add: "639 113 32 43",
    stud_email: "rsultan0@phoca.cz",
    stud_pass: "h4RmmdG",
  },
  {
    id: 2,
    first_name: "Molly",
    gender: "F",
    last_name: "Penvarden",
    age: 33,
    contact_add: "639 113 32 43",
    stud_email: "mpenvarden1@usa.gov",
    stud_pass: "BVmtq7oIXFu3",
  },
  {
    id: 3,
    first_name: "Peggie",
    last_name: "Batten",
    gender: "F",
    age: 26,
    contact_add: "639 113 32 43",
    stud_email: "pbatten2@oakley.com",
    stud_pass: "m7kKcQzUIgr",
  },
  {
    id: 4,
    first_name: "Celie",
    last_name: "Harry",
    gender: "F",
    age: 19,
    contact_add: "639 113 32 43",
    stud_email: "charry3@linkedin.com",
    stud_pass: "icUTKIH",
  },
  {
    id: 5,
    first_name: "Menard",
    last_name: "MacCawley",
    gender: "M",
    age: 29,
    contact_add: "639 113 32 43",
    stud_email: "mmaccawley4@mit.edu",
    stud_pass: "hDxXgw3aURP",
  },
];

export const directs = [
  {
    id: 1,
    first_name: "Johnson",
    last_name: "Sultan",
    gender: "M",
    age: 35,
    contact_add: "639 113 32 43",
    dir_email: "rsultan0@phoca.cz",
    dir_pass: "h4RmmdG",
  },
  {
    id: 2,
    first_name: "Molly",
    last_name: "Penvarden",
    gender: "F",
    age: 33,
    contact_add: "639 113 32 43",
    dir_email: "mpenvarden1@usa.gov",
    dir_pass: "BVmtq7oIXFu3",
  },
  {
    id: 3,
    first_name: "Peggie",
    last_name: "Batten",
    gender: "F",
    age: 26,
    contact_add: "639 113 32 43",
    dir_email: "pbatten2@oakley.com",
    dir_pass: "m7kKcQzUIgr",
  },
  {
    id: 4,
    first_name: "Celie",
    last_name: "Harry",
    gender: "F",
    age: 19,
    contact_add: "639 113 32 43",
    dir_email: "charry3@linkedin.com",
    dir_pass: "icUTKIH",
  },
  {
    id: 5,
    first_name: "Menard",
    last_name: "MacCawley",
    gender: "M",
    age: 29,
    contact_add: "639 113 32 43",
    dir_email: "mmaccawley4@mit.edu",
    dir_pass: "hDxXgw3aURP",
  },
];
export const admins = [
  {
    id: 1,
    first_name: "Johnson",
    last_name: "Sultan",
    gender: "M",
    age: 35,
    contact_add: "639 113 32 43",
    admin_email: "rsultan0@phoca.cz",
    admin_pass: "h4RmmdG",
  },
  {
    id: 2,
    first_name: "Molly",
    last_name: "Penvarden",
    gender: "F",
    age: 33,
    contact_add: "639 113 32 43",
    admin_email: "mpenvarden1@usa.gov",
    admin_pass: "BVmtq7oIXFu3",
  },
];

export const instructors = [
  {
    id: 1,
    first_name: "Reggi",
    last_name: "Cutbush",
    gender: "F",
    age: 47,
    contact_add: "639 113 32 43",
    ins_email: "rcutbush0@who.int",
    ins_pass: "ArPIrcjs9",
  },
  {
    id: 2,
    first_name: "Heinrick",
    last_name: "Tolwood",
    gender: "M",
    age: 80,
    contact_add: "639 113 32 43",
    ins_email: "htolwood1@comsenz.com",
    ins_pass: "PFiBUsjk5P",
  },
  {
    id: 3,
    first_name: "Fredelia",
    last_name: "Bye",
    gender: "F",
    age: 60,
    contact_add: "639 113 32 43",
    ins_email: "fbye2@virginia.edu",
    ins_pass: "b1US5aBGUeg",
  },
  {
    id: 4,
    first_name: "Jeffie",
    last_name: "Currie",
    gender: "M",
    age: 55,
    contact_add: "639 113 32 43",
    ins_email: "jcurrie3@mail.ru",
    ins_pass: "115Pah3",
  },
  {
    id: 5,
    first_name: "Mallissa",
    last_name: "Hospital",
    gender: "F",
    age: 53,
    contact_add: "639 113 32 43",
    ins_email: "mhospital4@privacy.gov.au",
    ins_pass: "mYBlZtMgUQH",
  },
  {
    id: 6,
    first_name: "Deck",
    last_name: "Reedy",
    gender: "M",
    age: 71,
    contact_add: "639 113 32 43",
    ins_email: "dreedy5@1und1.de",
    ins_pass: "M2k0GIzO9a6w",
  },
  {
    id: 7,
    first_name: "Merola",
    last_name: "Trittam",
    gender: "F",
    age: 31,
    contact_add: "639 113 32 43",
    ins_email: "mtrittam6@soundcloud.com",
    ins_pass: "8giixivcGU",
  },
  {
    id: 8,
    first_name: "Billie",
    last_name: "Moiser",
    gender: "F",
    age: 27,
    contact_add: "639 113 32 43",
    ins_email: "bmoiser7@guardian.co.uk",
    ins_pass: "YJYFqoEn",
  },
  {
    id: 9,
    first_name: "Sholom",
    last_name: "MacCracken",
    gender: "M",
    age: 34,
    contact_add: "639 113 32 43",
    ins_email: "smaccracken8@ted.com",
    ins_pass: "tRPyFCgJuI",
  },
  {
    id: 10,
    first_name: "Celka",
    last_name: "Kleinmann",
    gender: "F",
    age: 65,
    contact_add: "639 113 32 43",
    ins_email: "ckleinmann9@wikia.com",
    ins_pass: "hnlQcR",
  },
];

export const courses = [
  {
    id: 1,
    course_name: "Mate 1",
    course_desc: "",
    group: "",
  },
  {
    id: 2,
    course_name: "",
    course_desc: "",
    group: "",
  },
  {
    id: 3,
    course_name: "",
    course_desc: "",
    group: "",
  },
  {
    id: 4,
    course_name: "",
    course_desc: "",
    group: "",
  },
  {
    id: 5,
    course_name: "",
    course_desc: "",
    group: "",
  },
  {
    id: 6,
    course_name: "",
    course_desc: "",
    group: "",
  },
  {
    id: 7,
    course_name: "",
    course_desc: "",
    group: "",
  },
  {
    id: 8,
    course_name: "",
    course_desc: "",
    group: "",
  },
  {
    id: 9,
    course_name: "",
    course_desc: "",
    group: "",
  },
];

export const infoPropsStudent = {
  headId: [
    "stud_id",
    "first_name",
    "last_name",
    "gender",
    "age",
    "contact_add",
    "stud_email",
    "stud_pass",
    "actions",
  ],
  headLabels: [
    "ID",
    "Nombre",
    "Apellidos",
    "Genero",
    "Edad",
    "Telefono",
    "Email",
    "Clave",
    "Acciones",
  ],
};

export const infoPropsInstructor = {
  headId: [
    "id",
    "first_name",
    "last_name",
    "gender",
    "age",
    "contact_add",
    "ins_email",
    "ins_pass",
    "actions",
  ],
  headLabels: [
    "ID",
    "Nombre",
    "Apellidos",
    "Genero",
    "Edad",
    "Telefono",
    "Email",
    "Clave",
    "Acciones",
  ],
};
