export const subject = [
  {
    docName: "ENE-JUN-2021_electromechanical_math_1_A",
    refTeacher: null,
    nUnit: 6,
    student: [
      "Pr1@prepa7.com",
      "Pr2@prepa7.com",
      "Pr3@prepa7.com",
      "Pr4@prepa7.com",
      "Pr5@prepa7.com",
      "Pr6@prepa7.com",
      "Pr7@prepa7.com",
      "Pr8@prepa7.com",
      "Pr9@prepa7.com",
      "Pr10@prepa7.com",
    ],
  },
  {
    docName: "ENE-JUN-2021_electromechanical_physical_1_A",
    refTeacher: null,
    nUnit: 6,
    student: [
      "Pr1@prepa7.com",
      "Pr2@prepa7.com",
      "Pr3@prepa7.com",
      "Pr4@prepa7.com",
      "Pr5@prepa7.com",
      "Pr6@prepa7.com",
      "Pr7@prepa7.com",
      "Pr8@prepa7.com",
      "Pr9@prepa7.com",
      "Pr10@prepa7.com",
    ],
  },
  {
    docName: "ENE-JUN-2021_electromechanical_spanish_1_A",
    refTeacher: null,
    nUnit: 6,
    student: [
      "Pr1@prepa7.com",
      "Pr2@prepa7.com",
      "Pr3@prepa7.com",
      "Pr4@prepa7.com",
      "Pr5@prepa7.com",
      "Pr6@prepa7.com",
      "Pr7@prepa7.com",
      "Pr8@prepa7.com",
      "Pr9@prepa7.com",
      "Pr10@prepa7.com",
    ],
  },
];
