// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      first_name: "Carlye",
      last_name: "Trevaskiss",
      gender: "F",
      age: 25,
      contact_add: "639-115-10-67",
      email: "ctrevaskiss0@fotki.com",
      pass: "WSIq6XJy6vEw",
      math: 100,
      chinese: 0,
      english: 90,
      geography: 60,
      physics: 60,
      history: 40,
    },
    {
      id: 2,
      first_name: "Atalanta",
      last_name: "Ousby",
      gender: "F",
      age: 20,
      contact_add: "639-115-10-67",
      email: "aousby1@mysql.com",
      pass: "MkGn6M",
      math: 100,
      chinese: 70,
      english: 60,
      geography: 70,
      physics: 70,
      history: 40,
    },
    {
      id: 3,
      first_name: "Rosabel",
      last_name: "Lisciandro",
      gender: "F",
      age: 25,
      contact_add: "639-115-10-67",
      email: "rlisciandro2@va.gov",
      pass: "l7vReryTY0",
      math: 100,
      chinese: 100,
      english: 100,
      geography: 100,
      physics: 100,
      history: 100,
    },
    {
      id: 4,
      first_name: "Tad",
      last_name: "Rominov",
      gender: "M",
      age: 18,
      contact_add: "639-115-10-67",
      email: "trominov3@sitemeter.com",
      pass: "NoSiVU25MsCT",
      math: 80,
      chinese: 100,
      english: 70,
      geography: 60,
      physics: 60,
      history: 20,
    },
    {
      id: 5,
      first_name: "Klemens",
      last_name: "Meadus",
      gender: "M",
      age: 19,
      contact_add: "639-115-10-67",
      email: "kmeadus4@google.es",
      pass: "k5UV4mGk4",
      math: 100,
      chinese: 100,
      english: 70,
      geography: 90,
      physics: 60,
      history: 60,
    },
    {
      id: 6,
      first_name: "Thaddus",
      last_name: "Blaksland",
      gender: "M",
      age: 23,
      contact_add: "639-115-10-67",
      email: "tblaksland5@vimeo.com",
      pass: "jpj7Mo",
      math: 100,
      chinese: 70,
      english: 70,
      geography: 60,
      physics: 60,
      history: 40,
    },
    {
      id: 7,
      first_name: "Alberik",
      last_name: "Harder",
      gender: "M",
      age: 18,
      contact_add: "639-115-10-67",
      email: "aharder6@apache.org",
      pass: "kqihxF",
      math: 80,
      chinese: 90,
      english: 70,
      geography: 60,
      physics: 60,
      history: 40,
    },
    {
      id: 8,
      first_name: "Noak",
      last_name: "Goodburn",
      gender: "M",
      age: 24,
      contact_add: "639-115-10-67",
      email: "ngoodburn7@comcast.net",
      pass: "2FjssDHiKgG",
      math: 100,
      chinese: 90,
      english: 70,
      geography: 70,
      physics: 60,
      history: 40,
    },
    {
      id: 9,
      first_name: "Ignace",
      last_name: "Bauduccio",
      gender: "M",
      age: 19,
      contact_add: "639-115-10-67",
      email: "ibauduccio8@myspace.com",
      pass: "KcSppL65o",
      math: 100,
      chinese: 100,
      english: 60,
      geography: 60,
      physics: 60,
      history: 60,
    },
    {
      id: 10,
      first_name: "Bartie",
      last_name: "Gooda",
      gender: "M",
      age: 23,
      contact_add: "639-115-10-67",
      email: "bgooda9@apache.org",
      pass: "QkuHMw",
      math: 100,
      chinese: 100,
      english: 60,
      geography: 60,
      physics: 60,
      history: 40,
    },
    {
      id: 11,
      first_name: "Betty",
      last_name: "Linklet",
      gender: "F",
      age: 19,
      contact_add: "639-115-10-67",
      email: "blinkleta@wired.com",
      pass: "M6U4UCTuT",
      math: 90,
      chinese: 100,
      english: 70,
      geography: 70,
      physics: 60,
      history: 40,
    },
    {
      id: 12,
      first_name: "Tonye",
      last_name: "McDowell",
      gender: "F",
      age: 23,
      contact_add: "639-115-10-67",
      email: "tmcdowellb@odnoklassniki.ru",
      pass: "n8ydfZGzs",
      math: 90,
      chinese: 100,
      english: 60,
      geography: 90,
      physics: 60,
      history: 60,
    },
    {
      id: 13,
      first_name: "Hermine",
      last_name: "Smeuin",
      gender: "F",
      age: 23,
      contact_add: "639-115-10-67",
      email: "hsmeuinc@vkontakte.ru",
      pass: "fEQxahcLGBhK",
      math: 100,
      chinese: 70,
      english: 90,
      geography: 90,
      physics: 60,
      history: 20,
    },
    {
      id: 14,
      first_name: "Augusta",
      last_name: "Goldfinch",
      gender: "F",
      age: 24,
      contact_add: "639-115-10-67",
      email: "agoldfinchd@google.com.au",
      pass: "jD8HFjjuf",
      math: 100,
      chinese: 90,
      english: 60,
      geography: 70,
      physics: 60,
      history: 40,
    },
    {
      id: 15,
      first_name: "Ansell",
      last_name: "Pittman",
      gender: "M",
      age: 20,
      contact_add: "639-115-10-67",
      email: "apittmane@latimes.com",
      pass: "gyaFGR4NKN",
      math: 100,
      chinese: 70,
      english: 70,
      geography: 70,
      physics: 60,
      history: 40,
    },
    {
      id: 16,
      first_name: "Rubi",
      last_name: "Ewins",
      gender: "F",
      age: 23,
      contact_add: "639-115-10-67",
      email: "rewinsf@deliciousdays.com",
      pass: "MhsD1mHT8ITP",
      math: 90,
      chinese: 90,
      english: 90,
      geography: 60,
      physics: 70,
      history: 20,
    },
    {
      id: 17,
      first_name: "Horst",
      last_name: "Wolton",
      gender: "M",
      age: 18,
      contact_add: "639-115-10-67",
      email: "hwoltong@nyu.edu",
      pass: "U4l62Q2BXi",
      math: 100,
      chinese: 100,
      english: 70,
      geography: 60,
      physics: 60,
      history: 60,
    },
    {
      id: 18,
      first_name: "La verne",
      last_name: "Frandsen",
      gender: "F",
      age: 19,
      contact_add: "639-115-10-67",
      email: "lfrandsenh@stumbleupon.com",
      pass: "I5sLbEjHeApO",
      math: 90,
      chinese: 90,
      english: 90,
      geography: 90,
      physics: 60,
      history: 60,
    },
    {
      id: 19,
      first_name: "Nickie",
      last_name: "Hughson",
      gender: "M",
      age: 19,
      contact_add: "639-115-10-67",
      email: "nhughsoni@360.cn",
      pass: "acF8LJY",
      math: 90,
      chinese: 90,
      english: 60,
      geography: 60,
      physics: 60,
      history: 40,
    },
    {
      id: 20,
      first_name: "Stinky",
      last_name: "Grigolli",
      gender: "M",
      age: 23,
      contact_add: "639-115-10-67",
      email: "sgrigollij@umich.edu",
      pass: "7XkUgvrQ",
      math: 90,
      chinese: 100,
      english: 90,
      geography: 60,
      physics: 60,
      history: 60,
    },
    {
      id: 21,
      first_name: "Rex",
      last_name: "Methven",
      gender: "M",
      age: 25,
      contact_add: "639-115-10-67",
      email: "rmethvenk@gravatar.com",
      pass: "DTep2R5du",
      math: 100,
      chinese: 100,
      english: 70,
      geography: 90,
      physics: 60,
      history: 40,
    },
    {
      id: 22,
      first_name: "Minette",
      last_name: "Severwright",
      gender: "F",
      age: 25,
      contact_add: "639-115-10-67",
      email: "mseverwrightl@businesswire.com",
      pass: "MI1VSQZlg",
      math: 100,
      chinese: 70,
      english: 70,
      geography: 60,
      physics: 60,
      history: 60,
    },
    {
      id: 23,
      first_name: "Elston",
      last_name: "Belfitt",
      gender: "M",
      age: 18,
      contact_add: "639-115-10-67",
      email: "ebelfittm@answers.com",
      pass: "D4eeAcXp",
      math: 100,
      chinese: 70,
      english: 70,
      geography: 70,
      physics: 60,
      history: 20,
    },
    {
      id: 24,
      first_name: "Luciano",
      last_name: "Segot",
      gender: "M",
      age: 18,
      contact_add: "639-115-10-67",
      email: "lsegotn@samsung.com",
      pass: "Si4JaZG5G0p",
      math: 100,
      chinese: 100,
      english: 60,
      geography: 90,
      physics: 70,
      history: 40,
    },
    {
      id: 25,
      first_name: "Brose",
      last_name: "Pitson",
      gender: "M",
      age: 24,
      contact_add: "639-115-10-67",
      email: "bpitsono@blogtalkradio.com",
      pass: "ByihGsHaDVV",
      math: 100,
      chinese: 70,
      english: 70,
      geography: 90,
      physics: 60,
      history: 40,
    },
    {
      id: 26,
      first_name: "Cammie",
      last_name: "Gorrick",
      gender: "F",
      age: 25,
      contact_add: "639-115-10-67",
      email: "cgorrickp@mit.edu",
      pass: "JCdbUoGem",
      math: 90,
      chinese: 100,
      english: 90,
      geography: 60,
      physics: 60,
      history: 40,
    },
    {
      id: 27,
      first_name: "Dewie",
      last_name: "Rockey",
      gender: "M",
      age: 24,
      contact_add: "639-115-10-67",
      email: "drockeyq@ifeng.com",
      pass: "T5F0xEtv",
      math: 100,
      chinese: 70,
      english: 90,
      geography: 70,
      physics: 60,
      history: 60,
    },
    {
      id: 28,
      first_name: "Gray",
      last_name: "McClay",
      gender: "M",
      age: 22,
      contact_add: "639-115-10-67",
      email: "gmcclayr@walmart.com",
      pass: "UvyYsXN",
      math: 80,
      chinese: 100,
      english: 90,
      geography: 90,
      physics: 60,
      history: 60,
    },
    {
      id: 29,
      first_name: "Nikolos",
      last_name: "Luxen",
      gender: "M",
      age: 24,
      contact_add: "639-115-10-67",
      email: "nluxens@epa.gov",
      pass: "y4Y3Lj7",
      math: 80,
      chinese: 90,
      english: 90,
      geography: 90,
      physics: 70,
      history: 40,
    },
    {
      id: 30,
      first_name: "Tom",
      last_name: "Soames",
      gender: "M",
      age: 23,
      contact_add: "639-115-10-67",
      email: "tsoamest@usatoday.com",
      pass: "UShne7D38rOq",
      math: 90,
      chinese: 100,
      english: 60,
      geography: 70,
      physics: 60,
      history: 60,
    },
    {
      id: 31,
      first_name: "Augie",
      last_name: "Chmarny",
      gender: "M",
      age: 21,
      contact_add: "639-115-10-67",
      email: "achmarnyu@apple.com",
      pass: "uV9LLiKojL",
      math: 90,
      chinese: 100,
      english: 90,
      geography: 60,
      physics: 70,
      history: 40,
    },
    {
      id: 32,
      first_name: "Desiri",
      last_name: "Deacon",
      gender: "F",
      age: 19,
      contact_add: "639-115-10-67",
      email: "ddeaconv@deviantart.com",
      pass: "CDDEcy",
      math: 100,
      chinese: 90,
      english: 90,
      geography: 60,
      physics: 70,
      history: 20,
    },
    {
      id: 33,
      first_name: "Torry",
      last_name: "Traviss",
      gender: "M",
      age: 20,
      contact_add: "639-115-10-67",
      email: "ttravissw@surveymonkey.com",
      pass: "S8LH1yRG",
      math: 90,
      chinese: 70,
      english: 90,
      geography: 70,
      physics: 60,
      history: 60,
    },
    {
      id: 34,
      first_name: "Rockwell",
      last_name: "O'Dowd",
      gender: "M",
      age: 22,
      contact_add: "639-115-10-67",
      email: "rodowdx@shutterfly.com",
      pass: "8JJ3YMq",
      math: 100,
      chinese: 90,
      english: 60,
      geography: 70,
      physics: 60,
      history: 60,
    },
    {
      id: 35,
      first_name: "Emmye",
      last_name: "Latek",
      gender: "F",
      age: 25,
      contact_add: "639-115-10-67",
      email: "elateky@globo.com",
      pass: "7FEJ5qJO",
      math: 90,
      chinese: 90,
      english: 90,
      geography: 70,
      physics: 70,
      history: 40,
    },
    {
      id: 36,
      first_name: "Yanaton",
      last_name: "McGonagle",
      gender: "M",
      age: 19,
      contact_add: "639-115-10-67",
      email: "ymcgonaglez@devhub.com",
      pass: "LQDOCWO7",
      math: 80,
      chinese: 90,
      english: 70,
      geography: 60,
      physics: 60,
      history: 40,
    },
    {
      id: 37,
      first_name: "Dniren",
      last_name: "Cottle",
      gender: "F",
      age: 25,
      contact_add: "639-115-10-67",
      email: "dcottle10@hhs.gov",
      pass: "LogLPv",
      math: 90,
      chinese: 100,
      english: 90,
      geography: 90,
      physics: 70,
      history: 20,
    },
    {
      id: 38,
      first_name: "Cammy",
      last_name: "Leger",
      gender: "F",
      age: 23,
      contact_add: "639-115-10-67",
      email: "cleger11@army.mil",
      pass: "sSlD61",
      math: 80,
      chinese: 70,
      english: 60,
      geography: 90,
      physics: 60,
      history: 60,
    },
    {
      id: 39,
      first_name: "Puff",
      last_name: "Ebbetts",
      gender: "M",
      age: 19,
      contact_add: "639-115-10-67",
      email: "pebbetts12@twitpic.com",
      pass: "XfyjYZ",
      math: 90,
      chinese: 100,
      english: 70,
      geography: 70,
      physics: 60,
      history: 40,
    },
    {
      id: 40,
      first_name: "Mar",
      last_name: "Falconer-Taylor",
      gender: "M",
      age: 25,
      contact_add: "639-115-10-67",
      email: "mfalconertaylor13@yahoo.com",
      pass: "J2wKpkg",
      math: 100,
      chinese: 70,
      english: 60,
      geography: 60,
      physics: 60,
      history: 20,
    },
    {
      id: 41,
      first_name: "Lita",
      last_name: "Kiebes",
      gender: "F",
      age: 24,
      contact_add: "639-115-10-67",
      email: "lkiebes14@themeforest.net",
      pass: "R9fhvbwl",
      math: 100,
      chinese: 90,
      english: 90,
      geography: 60,
      physics: 60,
      history: 20,
    },
    {
      id: 42,
      first_name: "Benjie",
      last_name: "Vicary",
      gender: "M",
      age: 20,
      contact_add: "639-115-10-67",
      email: "bvicary15@fda.gov",
      pass: "KTNKxybT8",
      math: 80,
      chinese: 90,
      english: 60,
      geography: 70,
      physics: 60,
      history: 60,
    },
    {
      id: 43,
      first_name: "Jeremy",
      last_name: "Christophersen",
      gender: "M",
      age: 24,
      contact_add: "639-115-10-67",
      email: "jchristophersen16@prnewswire.com",
      pass: "K12yvYhW",
      math: 100,
      chinese: 70,
      english: 90,
      geography: 60,
      physics: 70,
      history: 20,
    },
    {
      id: 44,
      first_name: "Flin",
      last_name: "Burbidge",
      gender: "M",
      age: 24,
      contact_add: "639-115-10-67",
      email: "fburbidge17@netlog.com",
      pass: "wviJBM9",
      math: 80,
      chinese: 100,
      english: 60,
      geography: 70,
      physics: 60,
      history: 60,
    },
    {
      id: 45,
      first_name: "Karole",
      last_name: "Basant",
      gender: "F",
      age: 24,
      contact_add: "639-115-10-67",
      email: "kbasant18@bandcamp.com",
      pass: "g4AkCVcskC",
      math: 80,
      chinese: 90,
      english: 60,
      geography: 70,
      physics: 70,
      history: 40,
    },
    {
      id: 46,
      first_name: "Elissa",
      last_name: "Fawcett",
      gender: "F",
      age: 18,
      contact_add: "639-115-10-67",
      email: "efawcett19@cmu.edu",
      pass: "nV0F7j1vFtni",
      math: 100,
      chinese: 70,
      english: 90,
      geography: 90,
      physics: 70,
      history: 60,
    },
    {
      id: 47,
      first_name: "Margarita",
      last_name: "Van Der Hoog",
      gender: "F",
      age: 20,
      contact_add: "639-115-10-67",
      email: "mvanderhoog1a@mozilla.com",
      pass: "WzDKTehOc",
      math: 80,
      chinese: 70,
      english: 70,
      geography: 70,
      physics: 60,
      history: 20,
    },
    {
      id: 48,
      first_name: "Saunder",
      last_name: "Arden",
      gender: "M",
      age: 24,
      contact_add: "639-115-10-67",
      email: "sarden1b@sourceforge.net",
      pass: "RvA4ZiYwx",
      math: 90,
      chinese: 70,
      english: 90,
      geography: 70,
      physics: 70,
      history: 40,
    },
    {
      id: 49,
      first_name: "Sunshine",
      last_name: "Biggins",
      gender: "F",
      age: 21,
      contact_add: "639-115-10-67",
      email: "sbiggins1c@slideshare.net",
      pass: "YvEC6hY7s4W",
      math: 90,
      chinese: 100,
      english: 90,
      geography: 70,
      physics: 70,
      history: 60,
    },
    {
      id: 50,
      first_name: "Roanne",
      last_name: "De Ferrari",
      gender: "F",
      age: 19,
      contact_add: "639-115-10-67",
      email: "rdeferrari1d@kickstarter.com",
      pass: "h7HRfSxVE8h",
      math: 80,
      chinese: 90,
      english: 70,
      geography: 70,
      physics: 60,
      history: 20,
    },
  ]);
}
